Repository marcelropos/HM-DiscordBot, pull requests merged in 2021-08, with the labels that each got.

#19 Logger
  core/globalenum.py
  core/logger.py
  main.py
Labels: enhancement, ready for review

#26 Error handling
  core/error/error_collection.py
  core/error/error_handlers.py
  core/error/error_reply.py
  core/error/handler/base_handler.py
  core/error/handler/mongo_timeout_handler.py
  main.py
  mongo/gamingChannels.py
  mongo/mongoCollection.py
  mongo/primitiveMongoData.py
  mongo/studyChannels.py
  mongo/subjects.py
Labels: enhancement, ready for review

#29 Error handler
  core/error/error_collection.py
  core/error/error_handlers.py
  core/error/handler/bad_argument_handler.py
  core/error/handler/base_handler.py
  core/error/handler/bot_missing_permissions_handler.py
  core/error/handler/entry_not_found_handler.py
  core/error/handler/mongo_timeout_handler.py
Labels: enhancement, ready for review

#27 implementing mongo.py
  cogs/mongo.py
  core/error/handler/could_not_edit_entry_error_handler.py
  core/globalEnum.py
  mongo/primitiveMongoData.py
Labels: enhancement, ready for review

#31 implement loglevel controller
  cogs/logger.py
  core/error/handler/invalid_document_handler.py
  core/globalEnum.py
Labels: enhancement, ready for review

#30 implement admin.py
  cogs/admin.py
  core/error/handler/extension_already_loaded_handler.py
Labels: enhancement, ready for review

#28 Spielereien
  cogs/spielereien.py
  core/error/handler/man_page_not_found_handler.py
Labels: enhancement, ready for review

#38 Introduce help for commands.
  cogs/admin.py
  cogs/logger.py
  cogs/mongo.py
  cogs/spielereien.py
  core/error/handler/bad_argument_handler.py
  core/error/handler/value_error_handler.py
  main.py
Labels: documentation, enhancement, ready for review

#40 start implement predicates and add error(handler)
  core/error/error_collection.py
  core/error/handler/bad_bool_argument_handler.py
  core/error/handler/no_bot_chat_handler.py
  core/error/handler/no_multible_groups_handler.py
  core/error/handler/no_rules_handler.py
  core/predicates.py
Labels: enhancement, ready for review

#32 implement kick_ghosts.py
  cogs/kick_ghosts.py
  core/error/error_reply.py
  core/globalEnum.py
Labels: enhancement, ready for review

#41 correct inheritance.
  core/error/error_collection.py
Labels: ready for review, bugFix

#42 Study groups
  cogs/study_groups.py
  cogs/util/accepted_chats.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/place_holder.py
  cogs/util/study_subject_util.py
  core/error/error_collection.py
  core/error/handler/failed_to_grant_role_handler.py
  core/globalEnum.py
  core/predicates.py
  mongo/subjectsorgroups.py
Labels: enhancement, ready for review

#43 start implement little roles commands.
  cogs/roles.py
  core/error/error_collection.py
  core/globalEnum.py
  core/predicates.py
Labels: enhancement, ready for review

#44 implement moderator commands
  cogs/moderator.py
  cogs/roles.py
  cogs/study_groups.py
  cogs/util/assign_variables.py
  cogs/util/placeholder.py
  core/error/handler/command_on_cooldown_handler.py
  core/globalEnum.py
  core/predicates.py
Labels: enhancement, ready for review
