Repository marcelropos/HM-DiscordBot, pull requests merged in 2021-09, with the labels that each got.

#46 Small fixes
  core/logger.py
  requirements.txt
Labels: enhancement, ready for review

#45 Subjects
  cogs/groupSubjectLinking.py
  cogs/roles.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/assign_variables.py
  core/error/error_collection.py
  core/error/handler/bad_argument_handler.py
  core/error/handler/base_handler.py
  core/error/handler/default_handler.py
  core/error/handler/group_or_subject_not_found_handler.py
  core/error/handler/linking_not_found_handler.py
  core/globalEnum.py
  mongo/study_subject_relation.py
  requirements.txt
Labels: enhancement, ready for review

#47 Clean up
  cogs/admin.py
  cogs/bot_status.py
  cogs/group_subject_linking.py
  cogs/kick_ghosts.py
  cogs/logger.py
  cogs/moderator.py
  cogs/mongo.py
  cogs/roles.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/assign_variables.py
  cogs/util/study_subject_util.py
  core/error/error_collection.py
  core/error/handler/could_not_edit_entry_error_handler.py
  core/global_enum.py
  core/logger.py
  mongo/gaming_channels.py
  mongo/mongo_collection.py
  mongo/primitive_mongo_data.py
  mongo/study_channels.py
  mongo/study_subject_relation.py
  mongo/subjects_or_groups.py
Labels: documentation, ready for review

#49 Study/gaming channels
  cogs/gaming_channels.py
  cogs/moderator.py
  cogs/study_channels.py
  cogs/study_groups.py
  cogs/tmpc.py
  cogs/util/assign_variables.py
  cogs/util/study_subject_util.py
  cogs/util/tmp_channel_util.py
  cogs/util/voice_state_change.py
  core/error/error_collection.py
  core/error/handler/could_not_find_token_handler.py
  core/error/handler/may_not_use_command_error.py
  core/global_enum.py
  mongo/gaming_channels.py
  mongo/study_channels.py
  requirements.txt
Labels: enhancement, ready for review

#51 Nerd channel
  cogs/nerd_ecke.py
  cogs/study_channels.py
  core/global_enum.py
Labels: enhancement, ready for review

#52 Quick fixes
  cogs/group_subject_linking.py
  cogs/kick_ghosts.py
  cogs/roles.py
  cogs/spielereien.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/tmpc.py
  cogs/util/assign_variables.py
  cogs/util/tmp_channel_util.py
  core/error/handler/failed_to_grant_role_handler.py
  core/error/handler/no_bot_chat_handler.py
  core/error/handler/no_multible_groups_handler.py
Labels: ready for review

#57 added the tmp_studenty function
  cogs/grace_period.py
  cogs/kick_ghosts.py
  cogs/moderator.py
  cogs/roles.py
  cogs/spielereien.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/tmpc.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/placeholder.py
  core/error/handler/bot_missing_role_handler.py
  core/global_enum.py
  core/predicates.py
Labels: enhancement, ready for review

#59 Tmpc welcome message
  cogs/tmpc.py
  cogs/util/tmp_channel_util.py
Labels: documentation, ready for review

#61 implemented upgrade function
  cogs/logger.py
  cogs/upgrade.py
  cogs/util/study_subject_util.py
Labels: enhancement, ready for review

#62 Add subject colors and member grouping
  cogs/study_groups.py
  cogs/upgrade.py
  cogs/util/study_subject_util.py
  core/global_enum.py
Labels: enhancement, ready for review

#58 Documentation
  cogs/gaming_channels.py
  cogs/group_subject_linking.py
  cogs/moderator.py
  cogs/nerd_ecke.py
  cogs/roles.py
  cogs/study_channels.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/tmpc.py
  cogs/util/tmp_channel_util.py
Labels: documentation, ready for review

#63 Final touches
  .dockerignore
  README.md
  docker-compose.yml
  requirements.txt
Labels: enhancement, ready for review

#66 changed to take category permissions
  cogs/util/study_subject_util.py
  cogs/util/tmp_channel_util.py
  core/global_enum.py
Labels: ready for review, bugFix

#67 added edit group command
  cogs/study_groups.py
  docker-compose.yml
Labels: bugFix, next-semester

#72 Subject enumeration
  cogs/subjects.py
Labels: enhancement, ready for review

#74 deletes the last "Channel Deletion" message.
  cogs/util/tmp_channel_util.py
  core/global_enum.py
  mongo/study_channels.py
Labels: enhancement, ready for review

#76 log when a cog status has been changed.
  cogs/admin.py
  cogs/bot_status.py
  cogs/gaming_channels.py
  cogs/grace_period.py
  cogs/group_subject_linking.py
  cogs/kick_ghosts.py
  cogs/logger.py
  cogs/moderator.py
  cogs/mongo.py
  cogs/nerd_ecke.py
  cogs/roles.py
  cogs/spielereien.py
  cogs/study_channels.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/tmpc.py
  cogs/upgrade.py
Labels: enhancement, ready for review

#77 Temp channels
  cogs/tmpc.py
  cogs/util/tmp_channel_util.py
  core/global_enum.py
  mongo/study_channels.py
Labels: enhancement, ready for review
