Repository marcelropos/HM-DiscordBot, pull requests merged in 2022-02, with the labels that each got.

#91 removed restricted from code
  cogs/moderator.py
  core/global_enum.py
Labels: enhancement, ready for review

#92 added tmpc delete command
  cogs/tmpc.py
  cogs/util/tmp_channel_util.py
Labels: enhancement, ready for review

#93 Token show for everyone
  cogs/tmpc.py
Labels: ready for review, bugFix

#94 Disable all commands on upgrade
  cogs/upgrade.py
  main.py
Labels: enhancement, ready for review

#97 New version for the new semester
  cogs/moderator.py
  cogs/subjects.py
  cogs/tmpc.py
  cogs/upgrade.py
  cogs/util/tmp_channel_util.py
  core/global_enum.py
  main.py
Labels: enhancement, ready for review, bugFix

#98 improve Dockerfile
  Dockerfile
Labels: enhancement, ready for review

#99 Subjects
  cogs/subjects.py
  mongo/study_subject_relation.py
Labels: enhancement, ready for review
