Repository marcelropos/HM-DiscordBot, pull requests merged in 2023-09, with the labels that each got.

#111 Change to v2.0
  README.md
  cogs/admin.py
  cogs/bot_status.py
  cogs/grace_period.py
  cogs/group_subject_linking.py
  cogs/kick_ghosts.py
  cogs/logger.py
  cogs/moderator.py
  cogs/mongo.py
  cogs/nerd_ecke.py
  cogs/roles.py
  cogs/spielereien.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/temp_channels.py
  cogs/tmpc.py
  cogs/upgrade.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/assign_variables.py
  cogs/util/custom_select.py
  cogs/util/select_view.py
  cogs/util/tmp_channel_util.py
  core/error/error_reply.py
  core/error/handler/command_on_cooldown_handler.py
  core/error/handler/could_not_edit_entry_error_handler.py
  core/error/handler/leave_own_channel_handler.py
  core/logger.py
  core/predicates.py
  main.py
  mongo/join_temp_channels.py
  mongo/primitive_mongo_data.py
  mongo/study_subject_relation.py
  mongo/subjects_or_groups.py
  mongo/temp_channels.py
  requirements.txt
Labels: ready for review, Prio 1

#131 automatic deployment of the docker container
  .github/workflows/docker-image.yml
Labels: ready for review, Prio 2

#124 updates to master
  .github/workflows/docker-image.yml
  README.md
  cogs/admin.py
  cogs/bot_status.py
  cogs/grace_period.py
  cogs/group_subject_linking.py
  cogs/kick_ghosts.py
  cogs/logger.py
  cogs/moderator.py
  cogs/mongo.py
  cogs/nerd_ecke.py
  cogs/roles.py
  cogs/spielereien.py
  cogs/study_groups.py
  cogs/subjects.py
  cogs/temp_channels.py
  cogs/tmpc.py
  cogs/upgrade.py
  cogs/util/ainit_ctx_mgr.py
  cogs/util/assign_variables.py
  cogs/util/custom_select.py
  cogs/util/select_view.py
  cogs/util/tmp_channel_util.py
  core/error/error_reply.py
  core/error/handler/command_on_cooldown_handler.py
  core/error/handler/could_not_edit_entry_error_handler.py
  core/error/handler/leave_own_channel_handler.py
  core/logger.py
  core/predicates.py
  main.py
  mongo/join_temp_channels.py
  mongo/primitive_mongo_data.py
  mongo/study_subject_relation.py
  mongo/subjects_or_groups.py
  mongo/temp_channels.py
  requirements.txt
Labels: enhancement, ready for review, Prio 1

#132 fixed token place
  cogs/tmpc.py
Labels: ready for review, bugFix, Prio 2

#133 Ft add study groups
  cogs/study_groups.py
  cogs/upgrade.py
  cogs/util/study_subject_util.py
  core/global_enum.py
  mongo/primitive_mongo_data.py
Labels: enhancement, ready for review, Prio 1

#134 New Bot Version
  cogs/study_groups.py
  cogs/tmpc.py
  cogs/upgrade.py
  cogs/util/study_subject_util.py
  core/global_enum.py
  mongo/primitive_mongo_data.py
Labels: ready for review, next-semester, Prio 1

#135 hot fix for ghost roles
  cogs/kick_ghosts.py
Labels: ready for review, bugFix, Prio 1
