Repository marcelropos/HM-DiscordBot, pull requests merged in 2023-12, with the labels that each got.

#192 update dependencies
  Cargo.lock
  Cargo.toml
Labels: ready for review, Prio 2

#189 SQL methods
  Cargo.lock
  Cargo.toml
  migrations/20231117203935_foreignKeyCascade.sql
  migrations/20231119130517_fixDatatypes.sql
  migrations/20231206140137_fixDatatypes2.sql
  migrations/20231217145321_addChannelId.sql
  src/mysql_lib/mod.rs
  src/mysql_lib/test.rs
  src/mysql_lib/validate.rs
  src/redis_lib/mod.rs
Labels: ready for review, Prio 1

#193 Setup logging outputs and formatting
  Cargo.lock
  Cargo.toml
  src/bot/mod.rs
  src/logging.rs
  src/main.rs
  src/mysql_lib/mod.rs
Labels: ready for review

#194 Add permission checking methods
  Cargo.lock
  Cargo.toml
  src/bot/checks.rs
  src/bot/mod.rs
Labels: ready for review

#195 Env and struct fix
  src/bot/checks.rs
  src/bot/mod.rs
  src/env.rs
  src/logging.rs
  src/main.rs
  src/mysql_lib/mod.rs
  src/redis_lib/mod.rs
Labels: ready for review
