Repository marcelropos/HM-DiscordBot, pull requests merged in 2024-02, with the labels that each got.

#196 ✨ Add logger pipe command
  src/bot/checks.rs
  src/bot/commands.rs
  src/bot/mod.rs
  src/env.rs
  src/logging.rs
Labels: ready for review

#199 update dependencies
  Cargo.lock
  Cargo.toml
  Dockerfile
  src/bot/checks.rs
  src/bot/commands.rs
  src/bot/mod.rs
  src/logging.rs
  src/mysql_lib/mod.rs
  src/mysql_lib/test.rs
  src/mysql_lib/validate.rs
Labels: ready for review, Dependency

#202 changed Datatype of tmpc_keep_time
  migrations/20240218132517_changeTmpcKeepTimeDataType.sql
  src/mysql_lib/mod.rs
  src/mysql_lib/test.rs
Labels: ready for review, Database Migration

#201 added shutdown command
  src/bot/commands.rs
  src/bot/mod.rs
Labels: ready for review
